import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

function Login () {
    const [login, setLogin] = useState<boolean>(false);
    
    const onSubmit = () => {

    }

    return (
        <div className='relative flex flex-col w-screen h-screen bg-black md:items-center md:justify-center md:bg-transparent'>
            <Head>
				<title>BingeFlix</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
            
            <Image
                src='https://rb.gy/p2hphi'
                alt='Login Wallpaper'
                layout='fill'
                objectFit='cover'
                className='-z-10 !hidden opacity-60 sm:!inline'
            />

            <Image
                src='/img/logo-monochrome.svg'
                alt='BingeFlix Logo'
                width={150}
                height={100}
                layout='raw'
                className='absolute left-4 top-4 cursor-pointer object-contain md:left-10 md:top-6'
            />

            <form className='relative mt-24 space-y-8 py-10 px-6 rounded bg-black/75 md:mt-0 md:max-w-md md:px-14'>
                <h1 className='text-4xl font-semibold'>
                    Login
                </h1>
                <div className='space-y-4'>
                    <label htmlFor='email' className='inline-block w-full'>
                        <input type='email' id='email' placeholder='Email' className='loginInput' />
                    </label>
                    <label htmlFor='password' className='inline-block w-full'>
                        <input type='password' id='password' placeholder='Password' className='loginInput' />
                    </label>
                </div>

                <button
                    type='submit'
                    className='w-full rounded bg-primary py-3 font-semibold'
                >
                    Login
                </button>

                <div className='text-[grey]'>
                    <span>New to BingeFlix? </span>
                    <button
                        type='submit'
                        className='text-white hover:underline'
                    >
                        Sign up now!
                    </button>
                </div>
            </form>
        </div>
    );
};

export default Login;
